-- RLS was enabled (20260311120000) with no policies. For typical Supabase pooler roles,
-- that makes all rows invisible to SELECT — Prisma sees zero users and credentials auth
-- always fails with "invalid password". This app uses Prisma server-side, not Supabase
-- anon JWT; disable RLS again on these tables so the backend can query normally.

ALTER TABLE "User" DISABLE ROW LEVEL SECURITY;
ALTER TABLE "Account" DISABLE ROW LEVEL SECURITY;
ALTER TABLE "Session" DISABLE ROW LEVEL SECURITY;
ALTER TABLE "VerificationToken" DISABLE ROW LEVEL SECURITY;
ALTER TABLE "Collection" DISABLE ROW LEVEL SECURITY;
ALTER TABLE "Product" DISABLE ROW LEVEL SECURITY;
ALTER TABLE "ProductCollection" DISABLE ROW LEVEL SECURITY;
ALTER TABLE "ProductVariant" DISABLE ROW LEVEL SECURITY;
ALTER TABLE "ProductImage" DISABLE ROW LEVEL SECURITY;
ALTER TABLE "Provider" DISABLE ROW LEVEL SECURITY;
ALTER TABLE "ProviderSetting" DISABLE ROW LEVEL SECURITY;
ALTER TABLE "DefaultFulfillmentAddress" DISABLE ROW LEVEL SECURITY;
ALTER TABLE "ShippingRate" DISABLE ROW LEVEL SECURITY;
ALTER TABLE "ExternalProductMapping" DISABLE ROW LEVEL SECURITY;
ALTER TABLE "Inventory" DISABLE ROW LEVEL SECURITY;
ALTER TABLE "PendingCheckoutCart" DISABLE ROW LEVEL SECURITY;
ALTER TABLE "Order" DISABLE ROW LEVEL SECURITY;
ALTER TABLE "OrderItem" DISABLE ROW LEVEL SECURITY;
ALTER TABLE "Fulfillment" DISABLE ROW LEVEL SECURITY;
ALTER TABLE "FulfillmentItem" DISABLE ROW LEVEL SECURITY;
ALTER TABLE "Shipment" DISABLE ROW LEVEL SECURITY;
ALTER TABLE "PageView" DISABLE ROW LEVEL SECURITY;
